# Generated by Django 2.1.5 on 2019-02-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_emissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=3)),
                ('indicator_name', models.CharField(max_length=30)),
                ('indicator_code', models.CharField(max_length=30)),
                ('emission_values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country_population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=3)),
                ('indicator_name', models.CharField(max_length=30)),
                ('indicator_code', models.CharField(max_length=30)),
                ('population_values', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='emissions',
            name='country',
        ),
        migrations.RemoveField(
            model_name='population',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='emissions',
        ),
        migrations.DeleteModel(
            name='population',
        ),
    ]
