# Generated by Django 2.1.5 on 2019-02-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_auto_20190210_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_emissions',
            old_name='country_code',
            new_name='Country_Code',
        ),
        migrations.RenameField(
            model_name='country_emissions',
            old_name='country_name',
            new_name='Country_Name',
        ),
        migrations.RenameField(
            model_name='country_emissions',
            old_name='indicator_code',
            new_name='Indicator_Code',
        ),
        migrations.RenameField(
            model_name='country_emissions',
            old_name='indicator_name',
            new_name='Indicator_Name',
        ),
        migrations.RenameField(
            model_name='country_population',
            old_name='country_code',
            new_name='Country_Code',
        ),
        migrations.RenameField(
            model_name='country_population',
            old_name='country_name',
            new_name='Country_Name',
        ),
        migrations.RenameField(
            model_name='country_population',
            old_name='indicator_code',
            new_name='Indicator_Code',
        ),
        migrations.RenameField(
            model_name='country_population',
            old_name='indicator_name',
            new_name='Indicator_Name',
        ),
    ]
