# Generated by Django 2.1.5 on 2019-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_auto_20190225_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_emissions',
            name='Country_Name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='country_emissions',
            name='Indicator_Code',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='country_emissions',
            name='Indicator_Name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='country_population',
            name='Country_Name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='country_population',
            name='Indicator_Code',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='country_population',
            name='Indicator_Name',
            field=models.CharField(max_length=60),
        ),
    ]
